name: Update Lua Submodule

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "*/5 * * * *"

permissions:
  contents: write

concurrency:
  group: update-modules-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-modules:
    name: Update Modules
    runs-on: ubuntu-latest

    # https://stackoverflow.com/questions/64407333/using-github-actions-to-automatically-update-the-repos-submodules
    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Checkout latest release of Lua
      run: |
        url="https://api.github.com/repos/lua/lua/releases/latest"
        tag=$(curl -s "$url" | jq -r '.tag_name')
        cd upstream
        git checkout "$tag"
        cd ..
        git add upstream

    - name: Commit Update
      run: |
        git config --global user.name 'Lua Submodule Updater'
        git config --global user.email 'bot@noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Update Lua" && git push || echo "No changes to commit"
